name: Node.js CI/CD Pipeline

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: export PATH="$PATH:./node_modules/.bin" && jest --verbose
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Deploy to production
        run: npm run deploy
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          GMAIL_USER: ${{ secrets.GMAIL_USER}}
          GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
          SECRET: ${{ secrets.SECRET}}
          PORT: ${{ secrets.PORT}}








