name: Node.js CI/CD Pipeline

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
      
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install Dependencies
        run: npm install

  test:
    name: run-unit test
    runs-on: ubuntu-latest
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      GMAIL_USER: ${{ secrets.GMAIL_USER }}
      GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
      SECRET: ${{ secrets.SECRET }}
      PORT: ${{ secrets.PORT }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install Dependencies
        run: npm install
      - name: Run tests
        run: export PATH="$PATH:./node_modules/.bin" && jest --verbose --coverage

  deploy:
    runs-on: ubuntu-latest
    needs: [test, build]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Deploy to production
        run: npm run deploy
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          GMAIL_USER: ${{ secrets.GMAIL_USER}}
          GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
          SECRET: ${{ secrets.SECRET}}
          PORT: ${{ secrets.PORT}}
